### ISSUE TITLE
how do I install choco packages via OneGet Chocolatey provider?

### ISSUE THREAD

**Issue by rs38** [StefanScherer/chocolatey-packages#9]
> PS C:\Chocolatey\lib\docker.1.11.0-rc4\tools> .\chocolateyInstall.ps1
> Install-ChocolateyZipPackage : Die Benennung "Install-ChocolateyZipPackage" wurde nicht als Name eines Cmdlet, einer
> Funktion, einer Skriptdatei oder eines ausführbaren Programms erkannt. Überprüfen Sie die Schreibweise des Namens,

it seems a bit inconsistent to me, what's the clue?

**Comment by StefanScherer** [comment]
@rs38 Oh, that doesn't look so good. AFAIK the OneGet provider is a little outdated as the priority for Chocolatey is the 1.0 release. You might find answers in the Gitter channel https://gitter.im/chocolatey/chocolatey-oneget

**Comment by StefanScherer** [comment]
I'll close this as the choco package itself works fine with `choco install docker -pre`. It seems to be an issue with the OneGet provider.

**Comment by rs38** [comment]
there was an additional misunderstanding as I confused the single docker client with the new beta docker toolbox coming for Win+Mac. Would be nice to have it as a choco package if available.

**Comment by StefanScherer** [comment]
I think there will be a Chocolatey package as well. Cannot provide a package yet as it is a closed Beta for now.
